// components
export { default as MainLayout } from './templates/MainLayout/MainLayout'
export { default as ManagementLayout } from './templates/ManagementLayout'
export { default as Header } from './templates/Header/Header'
export { default as Sidebar } from './SideBar/SideBar'
export { default as Outlets } from './pages/Dashboard/Outlets'
export { default as FormSearch } from './pages/Kasir/Head/FormSearch'
export { default as Pagination } from './templates/Pagination'
export { default as TripleButtons } from './templates/TripleButtons'
export { default as NoData } from './templates/NoData'
export { default as FormGroup } from './templates/FormGroup'
export { default as Modal } from './templates/Modal'
export { default as Loading } from './templates/Loading'
export { default as Notification } from './templates/Notification'

// pages
export { default as Dashboard } from './pages/Dashboard/Dashboard'
export { default as Pengguna } from './pages/Pengguna/Pengguna'
export { default as RiwayatTransaksi } from './pages/RiwayatTransaksi'
export { default as Akun } from './pages/Akun'
export { default as Landing } from './pages/Landing'
export { default as NotFound } from './pages/NotFound'